version: '3'
services:
    job:
        build:
            context: .
            dockerfile: Dockerfile-job
        image: 'job:latest'
        volumes:
            - '.:${APP_DIRECTORY}'
            - '${APP_DIRECTORY}/node_modules'
        ports:
            - '${API_LOCAL_PORT}:${API_CONTAINER_PORT}'
        command:
            - ./wait-for-it.sh
            - 'db:${DB_CONTAINER_PORT}'
            - '--'
            - yarn
            - run
            - start
        environment:
            - 'API_CONTAINER_PORT=${API_CONTAINER_PORT}'
            - 'DB_CONTAINER_PORT=${DB_CONTAINER_PORT}'
            - 'DB_DATABASE_NAME=${DB_DATABASE_NAME}'
            - 'DB_CONTAINER_HOST=${DB_CONTAINER_HOST}'
            - 'DB_FORCE_DROP_DATABASE=${DB_FORCE_DROP_DATABASE}'
        restart: on-failure
        networks:
            - job
    db:
        build:
            context: .
            dockerfile: Dockerfile-db
        image: 'db:latest'
        volumes:
            - 'db-data:/data/db'
        ports:
            - '${DB_LOCAL_PORT}:${DB_CONTAINER_PORT}'
        restart: on-failure
        networks:
            - job
volumes:
    db-data: null
networks:
    job:
        driver: bridge